const drinks = [
  ['世界首創','珍珠奶茶',[['冰飲（小）',100],['冰飲（大）',190],['熱飲（小）',115],['熱飲（大）',220]]],
  ['發源','頂級烏瓦紅茶凍飲',[['冰飲（小）',85],['冰飲（大）',160],['熱飲（小）',100],['熱飲（大）',190]]],
  ['特別推薦','翡翠百香綠茶',[['冰飲（小）',120],['冰飲（大）',230]]],
  ['夏限定','四季春冰茶',[['冰飲（小）',90],['冰飲（大）',170]]],['夏限定','四季春紅柚蜜',[['冰飲（小）',130],['冰飲（大）',250]]],['夏限定','紅心芭樂檸檬茶',[['冰飲（小）',135],['冰飲（大）',260]]],
  ['茶加鮮奶','紅茶拿鐵',[['冰飲（小）',115],['冰飲（大）',220],['熱飲（小）',125],['熱飲（大）',240]]],['茶加鮮奶','鐵觀音拿鐵',[['冰飲（小）',115],['冰飲（大）',220],['熱飲（小）',125],['熱飲（大）',240]]],['茶加鮮奶','黑糖琥珀珍珠鮮奶',[['冰飲（小）',130],['冰飲（大）',250]]],
  ['醇奶茶','香醇奶茶',[['冰飲（小）',95],['冰飲（大）',180],['熱飲（小）',110],['熱飲（大）',210]]],['醇奶茶','胚芽奶茶',[['冰飲（小）',100],['冰飲（大）',190],['熱飲（小）',115],['熱飲（大）',220]]],['醇奶茶','茉香奶茶',[['冰飲（小）',95],['冰飲（大）',180],['熱飲（小）',110],['熱飲（大）',210]]],['醇奶茶','茉奶珍珠',[['冰飲（小）',100],['冰飲（大）',190],['熱飲（小）',115],['熱飲（大）',220]]],['醇奶茶','鐵觀音奶茶',[['冰飲（小）',95],['冰飲（大）',180],['熱飲（小）',110],['熱飲（大）',210]]],['醇奶茶','觀音珍珠奶茶',[['冰飲（小）',100],['冰飲（大）',190],['熱飲（小）',115],['熱飲（大）',220]]],
  ['純粹茶','鐵觀音凍飲',[['冰飲（小）',85],['冰飲（大）',160]]],['純粹茶','翡翠綠茶凍飲',[['冰飲（小）',90],['冰飲（大）',170]]],['調和茶','珍珠紅茶',[['冰飲（小）',90],['冰飲（大）',170]]],['調和茶','珍珠翡翠綠茶',[['冰飲（小）',90],['冰飲（大）',170]]],['調和茶','冰梅凍飲',[['冰飲（小）',95],['冰飲（大）',180],['熱飲（小）',110],['熱飲（大）',210]]],['調和茶','蜂蜜翡翠綠茶',[['冰飲（小）',95],['冰飲（大）',180]]],['調和茶','翡翠檸檬綠茶',[['冰飲（小）',110],['冰飲（大）',210]]],
  ['無茶類','檸檬蜜凍飲',[['冰飲（小）',105],['冰飲（大）',200]]],['無茶類','檸檬蘆薈凍飲',[['冰飲（小）',110],['冰飲（大）',210]]],['無茶類','蜂蜜拿鐵',[['冰飲（小）',115],['冰飲（大）',220],['熱飲（小）',125],['熱飲（大）',240]]]
];
const endpoint = window.ORDER_ENDPOINT || '';
const byId = id => document.getElementById(id);
const money = value => `$${Number(value).toLocaleString('zh-TW')}`;
function selectedDrink() { return drinks.find(([, name]) => name === byId('drink')?.value); }
function setVariants() { const drink = selectedDrink(); const select = byId('variant'); if (!drink || !select) return; select.innerHTML = drink[2].map(([label,price]) => `<option value="${label}" data-price="${price}">${label} · ${money(price)}</option>`).join(''); updateSummary(); }
function updateSummary() { const drink = selectedDrink(), option = byId('variant')?.selectedOptions[0], qty = Number(byId('quantity')?.value || 1), price = Number(option?.dataset.price || 0); if (!drink) return; byId('total').textContent = money(price * qty); byId('summary-drink').textContent = drink[1]; byId('summary-variant').textContent = option?.value || '—'; byId('summary-quantity').textContent = `${qty} 杯`; }
function ensureHiddenFields(form) { if (!byId('unit-price')) { const unitPrice = document.createElement('input'); unitPrice.type = 'hidden'; unitPrice.name = 'unitPrice'; unitPrice.id = 'unit-price'; form.appendChild(unitPrice); } if (!byId('total-price')) { const totalPrice = document.createElement('input'); totalPrice.type = 'hidden'; totalPrice.name = 'total'; totalPrice.id = 'total-price'; form.appendChild(totalPrice); } }
function ensureSubmitFrame() { if (byId('submit-frame')) return; const frame = document.createElement('iframe'); frame.id = 'submit-frame'; frame.name = 'submit-frame'; frame.style.display = 'none'; document.body.appendChild(frame); }
function populateForm() { const select = byId('drink'); const form = byId('order-form'); const variant = byId('variant'); const quantity = byId('quantity'); if (!select || !form || !variant || !quantity) return; const groups = {}; drinks.forEach(item => (groups[item[0]] ||= []).push(item)); select.innerHTML = Object.entries(groups).map(([category, items]) => `<optgroup label="${category}">${items.map(([,name]) => `<option value="${name}">${name}</option>`).join('')}</optgroup>`).join(''); setVariants(); select.addEventListener('change', setVariants); variant.addEventListener('change', updateSummary); quantity.addEventListener('input', updateSummary); document.querySelectorAll('[data-step]').forEach(button => button.addEventListener('click', () => { const input = byId('quantity'); input.value = Math.max(1, Math.min(20, Number(input.value || 1) + Number(button.dataset.step))); updateSummary(); })); form.addEventListener('submit', submitOrder); ensureHiddenFields(form); ensureSubmitFrame(); }
async function submitOrder(event) { event.preventDefault(); const name = byId('name').value.trim(), drink = selectedDrink(), option = byId('variant').selectedOptions[0], quantity = Number(byId('quantity').value), notice = byId('notice'); if (!name) { notice.textContent = '請先輸入姓名。'; byId('name').focus(); return; } if (!endpoint) { notice.textContent = '尚未設定 Google Sheet 串接網址，訂單未送出。'; return; } const order = {name, drink:drink[1], variant:option.value, unitPrice:Number(option.dataset.price), quantity, total:Number(option.dataset.price)*quantity}; const form = event.target; const button = event.submitter; button.disabled = true; notice.textContent = '正在送出…'; try { ensureHiddenFields(form); byId('unit-price').value = order.unitPrice; byId('total-price').value = order.total; form.action = endpoint; form.method = 'POST'; form.target = 'submit-frame'; form.submit(); notice.textContent = '已送出！謝謝你的點單。'; form.reset(); byId('quantity').value = 1; setVariants(); } catch (error) { notice.textContent = '送出失敗，請稍後再試。'; console.error(error); } finally { button.disabled = false; } }
async function loadOrders() { const message = byId('orders-message'), body = byId('orders-body'); if (!body) return; if (!endpoint) { message.textContent = 'Google Sheet 串接尚未設定。'; return; } try { const response = await fetch(endpoint); const data = await response.json(); const orders = data.orders || []; message.textContent = orders.length ? `共 ${orders.length} 筆訂單` : '目前尚無訂單。'; body.innerHTML = orders.map(order => `<tr><td>${order.time || ''}</td><td>${order.name || ''}</td><td>${order.drink || ''}</td><td>${order.variant || ''}</td><td>${order.quantity || ''}</td><td>${money(order.total || 0)}</td></tr>`).join(''); } catch { message.textContent = '目前無法讀取訂單，請稍後再試。'; } }
populateForm(); loadOrders();
